// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohigiedhjuqdlbohvssp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oaWdpZWRoanVxZGxib2h2c3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1Mjc0OTEsImV4cCI6MjA2OTEwMzQ5MX0.l2WZxLVdDoqEgYEOFxZNz8IfLVoYFyI4a9rhJc5DAM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});